/**
 * This file is autogenerated by Scaffold-HBAR.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-hbar/contract";

const deployedContracts = {
  296: {
    RouterExecutor: {
      address: "0x4d0049980a29A6C583163883D102F13AB6C74274",
      abi: [
        {
          inputs: [
            {
              internalType: "contract ISaucerV1Router",
              name: "v1Router_",
              type: "address",
            },
            {
              internalType: "contract ISaucerV2SwapRouter",
              name: "v2Router_",
              type: "address",
            },
            {
              internalType: "contract IERC20",
              name: "whbar_",
              type: "address",
            },
            {
              internalType: "contract IWhbarHelper",
              name: "whbarHelper_",
              type: "address",
            },
          ],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "token",
              type: "address",
            },
            {
              internalType: "int64",
              name: "responseCode",
              type: "int64",
            },
          ],
          name: "AssociationFailed",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint8",
              name: "venue",
              type: "uint8",
            },
          ],
          name: "BadVenue",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "deadline",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "blockTime",
              type: "uint256",
            },
          ],
          name: "Expired",
          type: "error",
        },
        {
          inputs: [],
          name: "HbarInputMustBeWhbar",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
          ],
          name: "HbarTransferFailed",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "totalOut",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "totalMinOut",
              type: "uint256",
            },
          ],
          name: "InsufficientOutput",
          type: "error",
        },
        {
          inputs: [],
          name: "NoLegs",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "legIndex",
              type: "uint256",
            },
          ],
          name: "PathMismatch",
          type: "error",
        },
        {
          inputs: [],
          name: "ReentrancyGuardReentrantCall",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "token",
              type: "address",
            },
          ],
          name: "SafeERC20FailedOperation",
          type: "error",
        },
        {
          inputs: [],
          name: "UnwrapRequiresWhbarOut",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "msgValue",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "totalIn",
              type: "uint256",
            },
          ],
          name: "ValueMismatch",
          type: "error",
        },
        {
          inputs: [],
          name: "ZeroRecipient",
          type: "error",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "sender",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "tokenIn",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "tokenOut",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amountIn",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "totalOut",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "bytes32",
              name: "planHash",
              type: "bytes32",
            },
          ],
          name: "RouteExecuted",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "token",
              type: "address",
            },
            {
              indexed: false,
              internalType: "int64",
              name: "responseCode",
              type: "int64",
            },
          ],
          name: "TokenAssociated",
          type: "event",
        },
        {
          inputs: [],
          name: "HTS",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "VENUE_V1",
          outputs: [
            {
              internalType: "uint8",
              name: "",
              type: "uint8",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "VENUE_V2",
          outputs: [
            {
              internalType: "uint8",
              name: "",
              type: "uint8",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          name: "associated",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "tokenIn",
              type: "address",
            },
            {
              internalType: "address",
              name: "tokenOut",
              type: "address",
            },
            {
              components: [
                {
                  internalType: "uint8",
                  name: "venue",
                  type: "uint8",
                },
                {
                  internalType: "bytes",
                  name: "path",
                  type: "bytes",
                },
                {
                  internalType: "uint256",
                  name: "amountIn",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "minOut",
                  type: "uint256",
                },
              ],
              internalType: "struct RouterExecutor.Leg[]",
              name: "legs",
              type: "tuple[]",
            },
            {
              internalType: "uint256",
              name: "totalMinOut",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "deadline",
              type: "uint256",
            },
            {
              internalType: "address",
              name: "recipient",
              type: "address",
            },
            {
              internalType: "bool",
              name: "unwrapToHbar",
              type: "bool",
            },
          ],
          name: "executeSplit",
          outputs: [
            {
              internalType: "uint256",
              name: "totalOut",
              type: "uint256",
            },
          ],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "tokenIn",
              type: "address",
            },
            {
              internalType: "address",
              name: "tokenOut",
              type: "address",
            },
            {
              components: [
                {
                  internalType: "uint8",
                  name: "venue",
                  type: "uint8",
                },
                {
                  internalType: "bytes",
                  name: "path",
                  type: "bytes",
                },
                {
                  internalType: "uint256",
                  name: "amountIn",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "minOut",
                  type: "uint256",
                },
              ],
              internalType: "struct RouterExecutor.Leg[]",
              name: "legs",
              type: "tuple[]",
            },
            {
              internalType: "uint256",
              name: "totalMinOut",
              type: "uint256",
            },
          ],
          name: "planHash",
          outputs: [
            {
              internalType: "bytes32",
              name: "",
              type: "bytes32",
            },
          ],
          stateMutability: "pure",
          type: "function",
        },
        {
          inputs: [],
          name: "v1Router",
          outputs: [
            {
              internalType: "contract ISaucerV1Router",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "v2Router",
          outputs: [
            {
              internalType: "contract ISaucerV2SwapRouter",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "whbar",
          outputs: [
            {
              internalType: "contract IERC20",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "whbarHelper",
          outputs: [
            {
              internalType: "contract IWhbarHelper",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          stateMutability: "payable",
          type: "receive",
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 41280884,
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
